# Daily test `nodejs` native connector 
# For it current develop branch's compatibility with latest TDengine's develop branch.
name: test compatibility

on:
  schedule:
    - cron: '0 2,14 * * *'
    # runner timezone is utc-0

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [10.x, 12.x]
    
    steps:

    - name: Build Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        sudo apt-get install -y python3 python3-pip python-is-python3

    - name: Checkout TDengine
      uses: actions/checkout@v3
      with:
          fetch-depth: 1
          repository: 'taosdata/TDengine'
          path: 'TDengine'
          ref: 'develop'
          submodules: 'recursive'

    - name: Build TDengine
      run: |
          cd TDengine
          mkdir debug
          cd debug
          cmake .. -DBUILD_JDBC=false -DBUILD_TOOLS=false
          make -j
          sudo make install
          
    - name: start taosd
      run: |
        nohup sudo taosd &
        taos -V  

    - name: start taosadapter
      run: |
        nohup sudo taosd &
        taos -V  

    - uses: actions/checkout@v3
      with:
          path : "node-taos"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: test nodejs
      working-directory: node-taos/nodejs
      run: |
        ls -al
        npm install
        npm run test

